### Class Demo from Section 4.2 of the notes

The file `rref.py` must be downloaded from Canvas - find it in computing assignment 1. Once you download it, upload it to syzygy and put it next to this file in the file manager.

In [1]:
import numpy as np
from rref import * 

rref package loaded successfully


### Example 4.3 of Section 4.2 of notes

In [2]:
# Example 4.3 in Section 4.2 of notes
A = np.array([[1,1,0],[1,0,1],[0,1,1]])
v = np.array([1,2,3])

aug_mat = np.column_stack([A,v])
print(aug_mat) # printing matrix to the screen for viewing

[[1 1 0 1]
 [1 0 1 2]
 [0 1 1 3]]


In [5]:
rref(aug_mat)

(array([[1., 0., 0., 0.],
        [0., 1., 0., 1.],
        [0., 0., 1., 2.]]),
 (0, 1, 2))

### Example 4.4 of Section 4.2 of notes

In [3]:
# Example 4.4
A = np.array([[1,0,1,2],[1,1,-1,1],[-1,3,2,4],[1,-1,-3,-3]])
A # this displays the matrix to the screen for viewing

array([[ 1,  0,  1,  2],
       [ 1,  1, -1,  1],
       [-1,  3,  2,  4],
       [ 1, -1, -3, -3]])

In [4]:
rref(A)

(array([[1., 0., 0., 1.],
        [0., 1., 0., 1.],
        [0., 0., 1., 1.],
        [0., 0., 0., 0.]]),
 (0, 1, 2))